image:
  name: ghcr.io/maison-de-la-simulation/nova:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git config --global --add safe.directory /builds/lrousselhard/nova/vendor/kokkos

stages:
  - build
  - test
  - deploy

build-job:serial:1:
  only: [ main, merge_requests ]
  stage: build
  needs: []
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror=vla -Werror=implicit-fallthrough" -DNovapp_NDIM=1 -DNovapp_SETUP=advection_gaussian -DNovapp_EOS=PERFECT -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -S . -B build
    - cmake --build build
  artifacts:
    expire_in: 1h
    paths:
      - build
      - bin

build-job:serial:2:
  only: [ main, merge_requests ]
  stage: build
  needs: []
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror=vla -Werror=implicit-fallthrough" -DNovapp_NDIM=2 -DNovapp_SETUP=advection_gaussian -DNovapp_EOS=PERFECT -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -S . -B build
    - cmake --build build
  artifacts:
    expire_in: 1h
    paths:
      - build
      - bin

build-job:serial:3:
  only: [ main, merge_requests ]
  stage: build
  needs: []
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror=vla -Werror=implicit-fallthrough" -DNovapp_NDIM=3 -DNovapp_SETUP=advection_gaussian -DNovapp_EOS=PERFECT -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -S . -B build
    - cmake --build build
  artifacts:
    expire_in: 1h
    paths:
      - build
      - bin

build-job:cuda:3:
  only: [ main, merge_requests ]
  stage: build
  needs: []
  script:
    - cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_CXX_COMPILER=$PWD/vendor/kokkos/bin/nvcc_wrapper -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror=vla -Werror=implicit-fallthrough" -DNovapp_NDIM=3 -DNovapp_SETUP=advection_gaussian -DNovapp_EOS=PERFECT -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_CONSTEXPR=ON -DKokkos_ARCH_AMPERE80=ON -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -S . -B build
    - cmake --build build

build-job:hip:3:
  only: [ main, merge_requests ]
  stage: build
  needs: []
  script:
    - cmake -DCMAKE_BUILD_TYPE=None -DCMAKE_CXX_COMPILER=hipcc -DBUILD_TESTING=OFF -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror=vla -Werror=implicit-fallthrough" -DNovapp_NDIM=3 -DNovapp_SETUP=advection_gaussian -DNovapp_EOS=PERFECT -DKokkos_ENABLE_HIP=ON -DKokkos_ARCH_VEGA90A=ON -DKokkos_ENABLE_DEPRECATED_CODE_3=OFF -DKokkos_ENABLE_DEBUG=ON -DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON -DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON -DKokkos_ENABLE_COMPILER_WARNINGS=ON -S . -B build
    - cmake --build build

unit-test-job:serial:1:
  only: [ main, merge_requests ]
  stage: test
  needs: ["build-job:serial:1"]
  script:
    - ctest --test-dir build --output-on-failure --timeout 5 --output-junit tests.xml
  artifacts:
    when: always
    reports:
      junit: build/tests.xml

unit-test-job:serial:2:
  only: [ main, merge_requests ]
  stage: test
  needs: ["build-job:serial:2"]
  script:
    - ctest --test-dir build --output-on-failure --timeout 5 --output-junit tests.xml
  artifacts:
    when: always
    reports:
      junit: build/tests.xml

unit-test-job:serial:3:
  only: [ main, merge_requests ]
  stage: test
  needs: ["build-job:serial:3"]
  script:
    - ctest --test-dir build --output-on-failure --timeout 5 --output-junit tests.xml
  artifacts:
    when: always
    reports:
      junit: build/tests.xml

convergence-advection-sinusoide-test-job:serial:1:
  only: [ main, merge_requests ]
  stage: test
  needs: ["build-job:serial:1"]
  script:
    - ./test/run_convergence_advection_gaussian.sh

format-job:
  only: [ main, merge_requests ]
  stage: test
  needs: []
  script:
    - find src tests -name '*.[h|c]pp' -exec clang-format --dry-run --ferror-limit=10 --Werror '{}' '+'
  allow_failure: true

lint-test-job:
  only: [ main, merge_requests ]
  stage: test
  needs: []
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."
